# Generated by Django 3.0.3 on 2022-05-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userofapp',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userofapp',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userofapp',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='userofapp',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userofapp',
            name='uaddr',
        ),
        migrations.RemoveField(
            model_name='userofapp',
            name='zip',
        ),
    ]
